import pandas as pd
import os
from config import CSV_PATH
from database import db

class CSVManager:
    def __init__(self):
            self.csv_path = CSV_PATH
                
                    def create_all_csv(self):
                            """Buat semua file CSV"""
                                    self.create_items_csv()
                                            self.create_monsters_csv()
                                                    self.create_achievements_csv()
                                                            self.create_quests_csv()
                                                                    self.create_game_config_csv()
                                                                            self.create_level_requirements_csv()
                                                                                    print("✅ Semua CSV berhasil dibuat")
                                                                                        
                                                                                            def create_items_csv(self):
                                                                                                    """Buat items.csv"""
                                                                                                            items_data = [
                                                                                                                            [1, "Roti", "🍞", 50, "consumable", "heal", 20, "common", "Makanan sederhana"],
                                                                                                                                        [2, "Ramuan Hidup", "💊", 100, "consumable", "heal", 50, "common", "Ramuan ajaib"],
                                                                                                                                                    [3, "Kristal Mistis", "🔮", 3000, "consumable", "heal", 100, "rare", "Kristal langka"],
                                                                                                                                                                [4, "Pedang Besi", "🗡️", 500, "weapon", "atk", 10, "common", "Pedang standar"],
                                                                                                                                                                            [5, "Pedang Kilat", "⚡", 2000, "weapon", "atk", 25, "rare", "Pedang petir"],
                                                                                                                                                                                        [6, "Pedang Naga", "🐉", 10000, "weapon", "atk", 50, "epic", "Pedang legendaris"],
                                                                                                                                                                                                    [7, "Perisai Kayu", "🛡️", 300, "armor", "def", 5, "common", "Perisai kayu"],
                                                                                                                                                                                                                [8, "Mahkota Emas", "👑", 5000, "armor", "def", 15, "rare", "Mahkota emas"],
                                                                                                                                                                                                                            [9, "Jubah Mistis", "🧥", 4000, "armor", "def", 12, "rare", "Jubah mistis"],
                                                                                                                                                                                                                                        [10, "Cincin Kekuatan", "💍", 1500, "accessory", "atk", 8, "uncommon", "Cincin kekuatan"],
                                                                                                            ]
                                                                                                                    
                                                                                                                            df = pd.DataFrame(items_data, columns=["item_id", "nama", "emoji", "harga", "tipe", "efek_type", "efek_value", "rarity", "deskripsi"])
                                                                                                                                    df.to_csv(f"{self.csv_path}items.csv", index=False)
                                                                                                                                        
                                                                                                                                            def create_monsters_csv(self):
                                                                                                                                                    """Buat monsters.csv"""
                                                                                                                                                            monsters_data = [
                                                                                                                                                                            [1, "Serigala Liar", "🐺", 1, 50, 12, 3, 25, 100, "Monster pemula"],
                                                                                                                                                                                        [2, "Goblin", "👹", 2, 60, 14, 4, 30, 120, "Makhluk nakal"],
                                                                                                                                                                                                    [3, "Zombie", "🧟", 3, 80, 15, 5, 40, 150, "Mayat hidup"],
                                                                                                                                                                                                                [4, "Orc", "🗡️", 4, 100, 18, 6, 50, 180, "Prajurit kuat"],
                                                                                                                                                                                                                            [5, "Naga Kecil", "🐉", 5, 120, 20, 8, 60, 250, "Naga muda"],
                                                                                                                                                                                                                                        [6, "Skeleton Knight", "💀", 6, 110, 22, 7, 65, 220, "Ksatria tulang"],
                                                                                                                                                                                                                                                    [7, "Demon", "😈", 8, 150, 25, 10, 80, 300, "Iblis kuat"],
                                                                                                                                                                                                                                                                [8, "Wyvern", "🦅", 10, 180, 30, 12, 100, 400, "Naga bersayap"],
                                                                                                                                                                                                                                                                            [9, "Dark Lord", "👿", 15, 250, 40, 15, 150, 600, "Penguasa kegelapan"],
                                                                                                                                                                                                                                                                                        [10, "Ancient Dragon", "🐲", 20, 300, 50, 20, 200, 800, "Naga kuno"],
                                                                                                                                                            ]
                                                                                                                                                                    
                                                                                                                                                                            df = pd.DataFrame(monsters_data, columns=["monster_id", "nama", "emoji", "level", "hp", "atk", "def", "exp", "koin", "deskripsi"])
                                                                                                                                                                                    df.to_csv(f"{self.csv_path}monsters.csv", index=False)
                                                                                                                                                                                        
                                                                                                                                                                                            def create_achievements_csv(self):
                                                                                                                                                                                                    """Buat achievements.csv"""
                                                                                                                                                                                                            achievements_data = [
                                                                                                                                                                                                                            [1, "Pemula", "🎮", "Buat karakter pertama", "create_character", 0, 0],
                                                                                                                                                                                                                                        [2, "Pemburu", "🐺", "Menang 5 battle", "win_5_battles", 100, 500],
                                                                                                                                                                                                                                                    [3, "Kaya Raya", "💰", "Kumpulkan 10000 koin", "collect_10000_coins", 200, 1000],
                                                                                                                                                                                                                                                                [4, "Penjelajah", "🗺️", "Jelajahi 20 kali", "explore_20_times", 150, 750],
                                                                                                                                                                                                                                                                            [5, "Kolektor", "🎁", "Kumpulkan 10 item langka", "collect_10_rare_items", 300, 1500],
                                                                                                                                                                                                                                                                                        [6, "Level Master", "⭐", "Capai level 10", "reach_level_10", 500, 2500],
                                                                                                                                                                                                                                                                                                    [7, "Pembunuh Naga", "🐉", "Kalahkan Naga Kecil", "defeat_small_dragon", 250, 1250],
                                                                                                                                                                                                                                                                                                                [8, "Legenda", "👑", "Capai level 20", "reach_level_20", 1000, 5000],
                                                                                                                                                                                                            ]
                                                                                                                                                                                                                    
                                                                                                                                                                                                                            df = pd.DataFrame(achievements_data, columns=["achievement_id", "nama", "emoji", "deskripsi", "kondisi", "reward_exp", "reward_koin"])
                                                                                                                                                                                                                                    df.to_csv(f"{self.csv_path}achievements.csv", index=False)
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                            def create_quests_csv(self):
                                                                                                                                                                                                                                                    """Buat quest_daily.csv"""
                                                                                                                                                                                                                                                            quests_data = [
                                                                                                                                                                                                                                                                            [1, "Pemburu Pemula", "🐺", "Kalahkan 5 monster", 5, 100, 500, "battle"],
                                                                                                                                                                                                                                                                                        [2, "Penjelajah Hutan", "🗺️", "Jelajahi 10 kali", 10, 150, 750, "explore"],
                                                                                                                                                                                                                                                                                                    [3, "Kolektor Item", "🎁", "Kumpulkan 5 item", 5, 80, 400, "collect"],
                                                                                                                                                                                                                                                                                                                [4, "Pembeli Setia", "🛍️", "Beli 3 item", 3, 50, 250, "shop"],
                                                                                                                                                                                                                                                                                                                            [5, "Penjual Handal", "💰", "Jual 3 item", 3, 50, 250, "shop"],
                                                                                                                                                                                                                                                            ]
                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                            df = pd.DataFrame(quests_data, columns=["quest_id", "nama_quest", "emoji", "deskripsi", "target_jumlah", "reward_exp", "reward_koin", "kategori"])
                                                                                                                                                                                                                                                                                    df.to_csv(f"{self.csv_path}quest_daily.csv", index=False)
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                            def create_game_config_csv(self):
                                                                                                                                                                                                                                                                                                    """Buat game_config.csv"""
                                                                                                                                                                                                                                                                                                            config_data = [
                                                                                                                                                                                                                                                                                                                            ["initial_hp", 100, "HP awal pemain"],
                                                                                                                                                                                                                                                                                                                                        ["initial_atk", 10, "ATK awal pemain"],
                                                                                                                                                                                                                                                                                                                                                    ["initial_def", 5, "DEF awal pemain"],
                                                                                                                                                                                                                                                                                                                                                                ["initial_koin", 0, "Koin awal pemain"],
                                                                                                                                                                                                                                                                                                                                                                            ["initial_level", 1, "Level awal pemain"],
                                                                                                                                                                                                                                                                                                                                                                                        ["exp_multiplier", 1.5, "Pengali EXP untuk level up"],
                                                                                                                                                                                                                                                                                                                                                                                                    ["hp_per_level", 20, "Penambahan HP per level"],
                                                                                                                                                                                                                                                                                                                                                                                                                ["atk_per_level", 5, "Penambahan ATK per level"],
                                                                                                                                                                                                                                                                                                                                                                                                                            ["def_per_level", 2, "Penambahan DEF per level"],
                                                                                                                                                                                                                                                                                                                                                                                                                                        ["battle_exp_base", 25, "EXP dasar dari battle"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                    ["battle_koin_base", 100, "Koin dasar dari battle"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                ["jelajah_exp_min", 10, "EXP minimum dari jelajah"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ["jelajah_exp_max", 30, "EXP maksimum dari jelajah"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ["jelajah_koin_min", 50, "Koin minimum dari jelajah"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ["jelajah_koin_max", 200, "Koin maksimum dari jelajah"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ["item_sell_percentage", 0.7, "Persentase harga jual item"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ["rare_item_drop_chance", 5, "Persentase drop item langka"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ["common_item_drop_chance", 40, "Persentase drop item biasa"],
                                                                                                                                                                                                                                                                                                            ]
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                            df = pd.DataFrame(config_data, columns=["config_key", "config_value", "deskripsi"])
                                                                                                                                                                                                                                                                                                                                    df.to_csv(f"{self.csv_path}game_config.csv", index=False)
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                            def create_level_requirements_csv(self):
                                                                                                                                                                                                                                                                                                                                                    """Buat level_requirements.csv"""
                                                                                                                                                                                                                                                                                                                                                            level_data = [
                                                                                                                                                                                                                                                                                                                                                                            [1, 0, 100, 10, 5, 100],
                                                                                                                                                                                                                                                                                                                                                                                        [2, 100, 120, 15, 8, 150],
                                                                                                                                                                                                                                                                                                                                                                                                    [3, 250, 140, 20, 10, 250],
                                                                                                                                                                                                                                                                                                                                                                                                                [4, 500, 160, 25, 12, 350],
                                                                                                                                                                                                                                                                                                                                                                                                                            [5, 1000, 200, 35, 20, 500],
                                                                                                                                                                                                                                                                                                                                                                                                                                        [6, 1500, 220, 40, 22, 600],
                                                                                                                                                                                                                                                                                                                                                                                                                                                    [7, 2250, 240, 45, 25, 750],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                [8, 3250, 260, 50, 28, 900],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            [9, 4500, 280, 55, 30, 1100],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        [10, 6000, 300, 60, 35, 1300],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    [15, 15000, 400, 80, 50, 2000],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                [20, 30000, 500, 100, 60, 3000],
                                                                                                                                                                                                                                                                                                                                                            ]
                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                            df = pd.DataFrame(level_data, columns=["level", "exp_needed", "hp_increase", "atk_increase", "def_increase", "max_exp_next_level"])
                                                                                                                                                                                                                                                                                                                                                                                    df.to_csv(f"{self.csv_path}level_requirements.csv", index=False)
                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                            def export_all_to_csv(self):
                                                                                                                                                                                                                                                                                                                                                                                                    """Export semua data dari database ke CSV"""
                                                                                                                                                                                                                                                                                                                                                                                                            db.export_to_csv()
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                    def import_all_from_csv(self):
                                                                                                                                                                                                                                                                                                                                                                                                                            """Import semua CSV ke database"""
                                                                                                                                                                                                                                                                                                                                                                                                                                    db.import_csv_to_db()

                                                                                                                                                                                                                                                                                                                                                                                                                                    # Inisialisasi CSV Manager
                                                                                                                                                                                                                                                                                                                                                                                                                                    csv_manager = CSVManager()
                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                            ]
                                                                                                                                                                                                                                                                                                            ]
                                                                                                                                                                                                                                                            ]
                                                                                                                                                                                                            ]
                                                                                                                                                            ]
                                                                                                            ]